import 'package:flutter/material.dart';
import 'package:game_tv/features/home/models/game_item.dart';

const globalTrailerGames = [
  GameItem(
    id: 24,
    title: 'CYBERLINE\n2077',
    subtitle: '',
    gradientStart: Color(0xFF0A1A3A),
    gradientEnd: Color(0xFF1A0A4A),
    date: '07 JUN 2024',
    category: 'upcoming',
  ),
  GameItem(
    id: 25,
    title: 'LAST OASIS\nONLINE',
    subtitle: '',
    gradientStart: Color(0xFF0A3A1A),
    gradientEnd: Color(0xFF1A2A0A),
    date: '02 AGO 2024',
    category: 'upcoming',
  ),

  GameItem(
    id: 21,
    title: 'ECLIPSE\nREBIRTH',
    subtitle: 'UN MUNDO CAE. UN HÉROE SE LEVANTA.',
    gradientStart: Color(0xFF1A0A3A),
    gradientEnd: Color(0xFF0D1B4A),
    badge: 'NUEVO LANZAMIENTO',
    date: '24 MAY 2024',
    category: 'hero',
  ),

  GameItem(
    id: 21,
    title: 'ECLIPSE\nREBIRTH',
    subtitle: 'UN MUNDO CAE. UN HÉROE SE LEVANTA.',
    gradientStart: Color(0xFF1A0A3A),
    gradientEnd: Color(0xFF0D1B4A),
    badge: 'NUEVO LANZAMIENTO',
    date: '24 MAY 2024',
    category: 'hero',
  ),
  GameItem(
    id: 22,
    title: 'NOVA\nFRONTIER',
    subtitle: 'EXPLORA LOS LÍMITES DEL UNIVERSO.',
    gradientStart: Color(0xFF1A2A0A),
    gradientEnd: Color(0xFF0A1A2A),
    date: '07 JUN 2024',
    category: 'hero',
  ),
  GameItem(
    id: 23,
    title: 'NEON\nDISTRICT',
    subtitle: 'LA CIUDAD NUNCA DUERME.',
    gradientStart: Color(0xFF0A1A3A),
    gradientEnd: Color(0xFF2A0A1A),
    date: '21 JUN 2024',
    category: 'hero',
  ),

  GameItem(
    id: 1,
    title: 'DUST\nSTORMS',
    subtitle: 'ACCIÓN',
    gradientStart: Color(0xFF3A2A0A),
    gradientEnd: Color(0xFF2A1A0A),
    category: 'new_releases',
  ),
  GameItem(
    id: 2,
    title: 'DEEP\nSEA',
    subtitle: 'SURVIVAL',
    gradientStart: Color(0xFF0A1A3A),
    gradientEnd: Color(0xFF0A0A2A),
    category: 'new_releases',
  ),
  GameItem(
    id: 3,
    title: 'GALACTIC\nRUN',
    subtitle: 'SCI-FI',
    gradientStart: Color(0xFF1A0A3A),
    gradientEnd: Color(0xFF0A0A2A),
    category: 'new_releases',
  ),
  GameItem(
    id: 4,
    title: 'FOREST\nKEEPER',
    subtitle: 'PUZZLE',
    gradientStart: Color(0xFF0A3A0A),
    gradientEnd: Color(0xFF0A1A0A),
    category: 'new_releases',
  ),
  GameItem(
    id: 5,
    title: 'BLOOD\nMOON',
    subtitle: 'HORROR',
    gradientStart: Color(0xFF3A0A0A),
    gradientEnd: Color(0xFF1A0A0A),
    category: 'new_releases',
  ),

  GameItem(
    id: 6,
    title: 'ELDEN\nSHADOW',
    subtitle: 'RPG DE ACCIÓN',
    gradientStart: Color(0xFF2A2A0A),
    gradientEnd: Color(0xFF1A1A0A),
    badge: '★ 9.8',
    category: 'top_rated',
  ),
  GameItem(
    id: 7,
    title: 'VOID\nWALKER',
    subtitle: 'SHOOTER TÁCTICO',
    gradientStart: Color(0xFF0A0A3A),
    gradientEnd: Color(0xFF1A0A2A),
    badge: '★ 9.5',
    category: 'top_rated',
  ),
  GameItem(
    id: 8,
    title: 'CRYSTAL\nSAGA',
    subtitle: 'RPG CLÁSICO',
    gradientStart: Color(0xFF0A2A2A),
    gradientEnd: Color(0xFF0A1A1A),
    badge: '★ 9.3',
    category: 'top_rated',
  ),
  GameItem(
    id: 9,
    title: 'IRON\nFORTRESS',
    subtitle: 'ESTRATEGIA',
    gradientStart: Color(0xFF2A1A0A),
    gradientEnd: Color(0xFF1A1A0A),
    badge: '★ 9.1',
    category: 'top_rated',
  ),
  GameItem(
    id: 10,
    title: 'PHANTOM\nGATE',
    subtitle: 'AVENTURA',
    gradientStart: Color(0xFF1A0A3A),
    gradientEnd: Color(0xFF0A0A2A),
    badge: '★ 9.0',
    category: 'top_rated',
  ),

  GameItem(
    id: 11,
    title: 'ECLIPSE\nREBIRTH',
    subtitle: 'TRÁILER DE LANZAMIENTO',
    gradientStart: Color(0xFF2A1A5A),
    gradientEnd: Color(0xFF0D1040),
    badge: 'NUEVO',
    category: 'trailers',
  ),

  GameItem(
    id: 12,
    title: 'NOVA\nFRONTIER',
    subtitle: 'GAMEPLAY OVERVIEW',
    gradientStart: Color(0xFF3A1A0A),
    gradientEnd: Color(0xFF1A0A20),
    category: 'trailers',
  ),

  GameItem(
    id: 13,
    title: 'NEON\nDISTRICT',
    subtitle: 'HISTORIA Y MUNDO',
    gradientStart: Color(0xFF0A2A3A),
    gradientEnd: Color(0xFF1A0A30),
    category: 'trailers',
  ),

  GameItem(
    id: 14,
    title: 'WHISPERS\nOF NATURE',
    subtitle: 'TRÁILER CINEMÁTICO',
    gradientStart: Color(0xFF0A3A1A),
    gradientEnd: Color(0xFF1A2A0A),
    category: 'trailers',
  ),

  GameItem(
    id: 15,
    title: 'ARENA\nKINGS',
    subtitle: 'TRÁILER OFICIAL',
    gradientStart: Color(0xFF3A2A0A),
    gradientEnd: Color(0xFF2A0A0A),
    category: 'trailers',
  ),

  GameItem(
    id: 16,
    title: 'CYBERLINE\n2077',
    subtitle: '',
    gradientStart: Color(0xFF0A1A3A),
    gradientEnd: Color(0xFF1A0A4A),
    date: '07 JUN 2024',
    category: 'upcoming',
  ),

  GameItem(
    id: 17,
    title: 'ARENA\nKINGS',
    subtitle: '',
    gradientStart: Color(0xFF3A1A0A),
    gradientEnd: Color(0xFF2A0A10),
    date: '21 JUN 2024',
    category: 'upcoming',
  ),

  GameItem(
    id: 18,
    title: 'STARFALL\nLEGACY',
    subtitle: '',
    gradientStart: Color(0xFF0A2A3A),
    gradientEnd: Color(0xFF0A1A2A),
    date: '05 JUL 2024',
    category: 'upcoming',
  ),

  GameItem(
    id: 19,
    title: 'MONSTER\nHUNTERS',
    subtitle: '',
    gradientStart: Color(0xFF2A0A3A),
    gradientEnd: Color(0xFF1A0A20),
    date: '19 JUL 2024',
    category: 'upcoming',
  ),

  GameItem(
    id: 20,
    title: 'LAST OASIS\nONLINE',
    subtitle: '',
    gradientStart: Color(0xFF0A3A1A),
    gradientEnd: Color(0xFF1A2A0A),
    date: '02 AGO 2024',
    category: 'upcoming',
  ),
];
